on: push
name: Smoke test
jobs:
  test:
    strategy:
      matrix:
        node-version: [10, 12]
        os: [ubuntu-latest, windows-latest, macos-latest]
        elm-version: [latest-0.19.0, latest-0.19.1]
    name: Test with Elm ${{matrix.elm-version}} on Node ${{ matrix.node-version }} and ${{ matrix.os }}
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@master
    - name: Build
      uses: actions/setup-node@master
      with:
        args: npm install
    - name: Install Elm
      uses: actions/setup-node@master
      with:
        version: ${{ matrix.node-version }}
        args: npm install elm@${{ matrix.elm-version }}
    - name: Test
      uses: actions/setup-node@master
      with:
        args: npm test
