on: push
name: Build & Test
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build
      uses: actions/setup-node@master
      with:
        args: npm install
    - name: Install Elm
      uses: actions/setup-node@master
      with:
        args: npm install elm@0.19.0
    - name: Test
      uses: actions/setup-node@master
      with:
        args: npm test
